Repository WhatToDo6/WhatToDo, pull requests merged in 2024-04, with the labels that each got.

#10 box-sizing 속성 추가 / pr 템플릿 추가
  .github/pull_request_template.md
  src/styles/reset.css
Labels: fix, style

#9 로그인, 회원가입 페이지 UI
  package-lock.json
  package.json
  pages/login/index.tsx
  pages/signup/index.tsx
  public/icons/eye-off.svg
  public/icons/eye-on.svg
  public/images/logo-img.png
  public/images/logo-text.svg
  src/components/login-signup/button/Button.module.scss
  src/components/login-signup/button/index.tsx
  src/components/login-signup/change-page/ChagePage.module.scss
  src/components/login-signup/change-page/index.tsx
  src/components/login-signup/form/Form.module.scss
  src/components/login-signup/form/login/index.tsx
  src/components/login-signup/form/signup/index.tsx
  src/components/login-signup/input/Input.module.scss
  src/components/login-signup/input/login/index.tsx
  src/components/login-signup/input/signup/index.tsx
  src/components/login-signup/layout/Layout.module.scss
  src/components/login-signup/layout/index.tsx
  src/components/login-signup/welcome-logo/WelcomLogo.module.scss
  src/components/login-signup/welcome-logo/index.tsx
Labels: ui

#12 대시보드 페이지 컴포넌트 기초 UI 구현
  pages/dashboard/test.tsx
  src/components/dashboard/dashboard-button/dashboardButton.module.scss
  src/components/dashboard/dashboard-button/index.tsx
  src/components/dashboard/header/DashboardHeader.module.scss
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/InvitedDashboard.module.scss
  src/components/dashboard/invited-list/index.tsx
  src/components/dashboard/invited-list/invite-card/InviteCard.module.scss
  src/components/dashboard/invited-list/invite-card/index.tsx
Labels: ui

#18 Button 컴포넌트 반응형
  src/components/common/button/basic/BasicButton.module.scss
  src/components/common/button/basic/index.tsx
  src/components/common/button/border/BorderButton.module.scss
  src/components/common/button/option/OptionButton.module.scss
  src/components/common/button/option/index.tsx
Labels: ui

#11 대시보드[id] 페이지 사이드 바 ui
  pages/dashboard/[id]/index.tsx
  pages/dashboard/index.tsx
  public/icons/add-box.svg
  public/icons/crown-icon.svg
  src/components/common/layout/Layout.module.scss
  src/components/common/layout/index.tsx
  src/components/dashboard/side-menu/SideMenu.module.scss
  src/components/dashboard/side-menu/constants.js
  src/components/dashboard/side-menu/dashboard-list-section/DashboardListSection.module.scss
  src/components/dashboard/side-menu/dashboard-list-section/dashboard-list/DashboardList.module.scss
  src/components/dashboard/side-menu/dashboard-list-section/dashboard-list/index.tsx
  src/components/dashboard/side-menu/dashboard-list-section/index.tsx
  src/components/dashboard/side-menu/dashboard-list-section/list-header/ListHeader.module.scss
  src/components/dashboard/side-menu/dashboard-list-section/list-header/index.tsx
  src/components/dashboard/side-menu/index.tsx
  src/constants/route.js
Labels: ui

#20 feat: 폰트 적용
  public/fonts/Montserrat/Montserrat-SemiBold.ttf
  public/fonts/Pretendard/Pretendard-Black.woff
  public/fonts/Pretendard/Pretendard-Bold.woff
  public/fonts/Pretendard/Pretendard-ExtraBold.woff
  public/fonts/Pretendard/Pretendard-ExtraLight.woff
  public/fonts/Pretendard/Pretendard-Light.woff
  public/fonts/Pretendard/Pretendard-Medium.woff
  public/fonts/Pretendard/Pretendard-Regular.woff
  public/fonts/Pretendard/Pretendard-SemiBold.woff
  public/fonts/Pretendard/Pretendard-Thin.woff
  src/styles/font-family.css
  src/styles/reset.css
Labels: feat

#23 대시보드 nav 구현 후 적용, 대시보드 페이지 무한스크롤, 검색 기능 구현
  pages/dashboard/Dashboard.module.scss
  pages/dashboard/index.tsx
  pages/dashboard/test.tsx
  public/icons/add-board-btn.svg
  public/icons/add-box-icon.svg
  public/icons/bar.svg
  public/icons/magnifying-glass-icon.svg
  public/icons/right-arrow.svg
  public/icons/setting-icon.svg
  public/icons/temp-circle-1.svg
  public/icons/temp-circle-2.svg
  public/icons/temp-circle-3.svg
  public/icons/temp-circle-4.svg
  public/icons/temp-circle-5.svg
  public/icons/temp-circle-6.svg
  public/images/empty-board-img.png
  src/components/common/layout/Layout.module.scss
  src/components/common/layout/index.tsx
  src/components/dashboard/dashboard-button/dashboardButton.module.scss
  src/components/dashboard/dashboard-button/index.tsx
  src/components/dashboard/header/DashboardHeader.module.scss
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/InvitedDashboard.module.scss
  src/components/dashboard/invited-list/index.tsx
  src/components/dashboard/invited-list/invite-card/InviteCard.module.scss
  src/components/dashboard/invited-list/invite-card/index.tsx
  src/hooks/useInputSearch.ts
  src/hooks/useInterSectionObserver.ts
Labels: feat, ui

#25 API 세팅 및 INPUT 공통 컴포넌트
  lib/axios.ts
  package-lock.json
  package.json
  src/components/common/input/Input.module.scss
  src/components/common/input/email/Email.module.scss
  src/components/common/input/email/index.tsx
  src/components/common/input/index.tsx
  src/components/common/input/password-check/index.tsx
  src/components/common/input/password/Password.module.scss
  src/components/common/input/password/index.tsx
  src/components/common/input/text/Text.module.scss
  src/components/common/input/text/index.tsx
  src/components/login-signup/form/signup/index.tsx
  src/components/login-signup/welcome-logo/index.tsx
  src/types/input.ts
  src/utils/validation.ts
Labels: feat, ui

#21 계정 관리 UI, 비밀번호 에러 메세지 구현
  pages/mypage/index.tsx
  public/icons/add-img.svg
  public/icons/left-arrow.svg
  src/components/common/button/border/BorderButton.module.scss
  src/components/common/button/border/index.tsx
  src/components/mypage/content/Content.module.scss
  src/components/mypage/content/index.tsx
  src/components/mypage/input/Input.module.scss
  src/components/mypage/input/index.tsx
  src/components/mypage/password/Password.module.scss
  src/components/mypage/password/index.tsx
  src/components/mypage/profile/Profile.module.scss
  src/components/mypage/profile/index.tsx
Labels: feat, ui

#28 Input text 공통 컴포넌트 세분화
  src/components/common/input/index.tsx
  src/components/common/input/text/index.tsx
  src/components/login-signup/form/login/index.tsx
  src/components/login-signup/form/signup/index.tsx
  src/types/input.ts
Labels: refactor

#26 로그인 기능 구현
  src/components/login-signup/form/login/index.tsx
Labels: feat

#29 font-family 적용 안 되는 현상 수정
  pages/_document.tsx
  public/fonts/Montserrat/Montserrat-SemiBold.ttf
  public/fonts/Pretendard/Pretendard-Black.woff
  public/fonts/Pretendard/Pretendard-Bold.woff
  public/fonts/Pretendard/Pretendard-ExtraBold.woff
  public/fonts/Pretendard/Pretendard-ExtraLight.woff
  public/fonts/Pretendard/Pretendard-Light.woff
  public/fonts/Pretendard/Pretendard-Medium.woff
  public/fonts/Pretendard/Pretendard-Regular.woff
  public/fonts/Pretendard/Pretendard-SemiBold.woff
  public/fonts/Pretendard/Pretendard-Thin.woff
  src/styles/reset.css
Labels: fix

#38 로그인하기 버튼 클릭 시 이동 구현
  src/components/landing/header/index.tsx
Labels: feat

#37 대시보드 페이지 컴포넌트 마무리, 대시보드 버튼 공통으로 쓸수 있게 변경
  pages/dashboard/Dashboard.module.scss
  pages/dashboard/index.tsx
  pages/dashboard/test.tsx
  public/images/small-arrow-left.png
  public/images/small-arrow-right.png
  src/components/common/layout/index.tsx
  src/components/dashboard/button-container/buttonContainer.module.scss
  src/components/dashboard/button-container/index.tsx
  src/components/dashboard/dashboard-button/dashboardButton.module.scss
  src/components/dashboard/dashboard-button/index.tsx
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/InvitedList.module.scss
  src/components/dashboard/invited-list/index.tsx
  src/components/dashboard/pagenation-button/PagenationButton.module.scss
  src/components/dashboard/pagenation-button/index.tsx
  src/hooks/usePagenation.ts
Labels: feat, ui

#48 공통 모달 컴포넌트
  src/components/common/modal/Modal.module.scss
  src/components/common/modal/index.tsx
  src/components/common/modal/modal-alert/ModalAlert.module.scss
  src/components/common/modal/modal-alert/index.tsx
  src/components/login-signup/form/login/index.tsx
  src/components/login-signup/form/signup/index.tsx
  src/components/login-signup/input/Input.module.scss
  src/components/login-signup/input/login/index.tsx
  src/components/login-signup/input/signup/index.tsx
  src/components/login-signup/layout/Layout.module.scss
Labels: feat, ui

#40 메인 페이지 리다이렉트 설정
  pages/index.tsx
  src/constants/route.js
Labels: feat

#45 dashboard[id] 페이지 ui 작업 완료 (재업로드)
  pages/dashboard/[id]/DashboardId.module.scss
  pages/dashboard/[id]/index.tsx
  public/icons/calendar.svg
  public/images/task-card-img.png
  src/components/dashboard/column/Column.module.scss
  src/components/dashboard/column/column-header/ColumnHeader.module.scss
  src/components/dashboard/column/column-header/index.tsx
  src/components/dashboard/column/column-layout/ColumnLayout.module.scss
  src/components/dashboard/column/column-layout/index.tsx
  src/components/dashboard/column/constants.js
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card-date/TaskCardDate.module.scss
  src/components/dashboard/column/task-card-date/index.tsx
  src/components/dashboard/column/task-card-tag/TaskCardTag.module.scss
  src/components/dashboard/column/task-card-tag/index.tsx
  src/components/dashboard/column/task-card/TaskCard.module.scss
  src/components/dashboard/column/task-card/index.tsx
  src/components/dashboard/dashboard-button/dashboardButton.module.scss
Labels: fix, feat

#49 계정 관리 API
  src/components/common/input/index.tsx
  src/components/common/input/text/Text.module.scss
  src/components/common/input/text/index.tsx
  src/components/mypage/password/Password.module.scss
  src/components/mypage/password/index.tsx
  src/components/mypage/profile-form/ProfileForm.module.scss
  src/components/mypage/profile-form/index.tsx
  src/components/mypage/profile/Profile.module.scss
  src/components/mypage/profile/index.tsx
  src/hooks/useUserData.tsx
  src/types/input.ts
Labels: feat, refactor

#53 대시보드 수정 페이지 컴포넌트 생성
  pages/dashboard/index.tsx
  public/icons/add-box-icon-white.svg
  src/components/common/button/border/BorderButton.module.scss
  src/components/common/button/border/index.tsx
  src/components/dashboard/button-container/buttonContainer.module.scss
  src/components/dashboard/invited-list/InvitedList.module.scss
  src/components/dashboard/invited-list/card/InviteCard.module.scss
  src/components/dashboard/invited-list/card/index.tsx
  src/components/dashboard/invited-list/dashboard/InviteListDashboard.module.scss
  src/components/dashboard/invited-list/dashboard/index.tsx
  src/components/dashboard/invited-list/email/InviteListEmail.module.scss
  src/components/dashboard/invited-list/email/index.tsx
  src/components/dashboard/invited-list/index.tsx
  src/components/dashboard/invited-list/invite-card/InviteCard.module.scss
  src/components/dashboard/invited-list/invite-card/index.tsx
  src/components/dashboard/invited-list/member/InviteListMember.module.scss
  src/components/dashboard/invited-list/member/index.tsx
  src/components/dashboard/pagenation-button/PagenationButton.module.scss
Labels: feat, ui

#55 비밀번호 변경 모달 적용
  src/components/common/modal/modal-alert/ModalAlert.module.scss
  src/components/mypage/password/index.tsx
Labels: feat

#66 절대경로로 변경
  src/components/common/button/basic/BasicButton.module.scss
  src/components/common/button/border/BorderButton.module.scss
  src/components/common/button/option/OptionButton.module.scss
  src/components/landing/feature-content/FeatureContent.module.scss
  src/components/landing/feature-content/index.tsx
  src/components/landing/footer/Footer.module.scss
  src/components/landing/footer/constants.ts
  src/components/landing/header/Header.module.scss
  src/components/landing/header/index.tsx
  src/components/landing/navigation/Navigaiton.module.scss
  src/components/landing/navigation/index.tsx
  src/components/landing/settings-content/SettingsContent.module.scss
  src/components/landing/settings-content/constants.ts
  src/components/mypage/content/Content.module.scss
  src/components/mypage/content/index.tsx
  src/components/mypage/password/Password.module.scss
  src/components/mypage/password/index.tsx
  src/components/mypage/profile-form/ProfileForm.module.scss
  src/components/mypage/profile-form/index.tsx
  src/components/mypage/profile/Profile.module.scss
  src/hooks/useUserData.ts
Labels: refactor

#67 api 요청으로 대시보드 리스트 받아온 후 대시보드 리스트 버튼에 적용, /dashboard -> /mydashboard로 경로 변경
  pages/mydashboard/MyDashboard.module.scss
  pages/mydashboard/index.tsx
  src/components/dashboard/button-container/index.tsx
  src/components/dashboard/dashboard-button/dashboardButton.module.scss
  src/components/dashboard/dashboard-button/index.tsx
  src/components/dashboard/invited-list/dashboard/index.tsx
  src/hooks/useInterSectionObserver.ts
  src/hooks/usePagenationTest.ts
Labels: feat

#69 ColorChip 컴포넌트 생성
  public/icons/check.svg
  src/components/common/chip/ColorChip.module.scss
  src/components/common/chip/index.tsx
Labels: feat

#68 이미지 업로드 input 분리
  src/components/common/input/image-upload/ImageUpload.module.scss
  src/components/common/input/image-upload/index.tsx
  src/components/mypage/profile-form/ProfileForm.module.scss
  src/components/mypage/profile-form/index.tsx
Labels: feat

#65 모달 Portals 적용 및 modal-todo
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  public/icons/calendar-black.svg
  public/icons/calendar-gray.svg
  src/components/common/input/Input.module.scss
  src/components/common/input/date/Date.module.scss
  src/components/common/input/date/index.tsx
  src/components/common/input/date/react-datepicker.css
  src/components/common/input/index.tsx
  src/components/common/input/tag/Tag.module.scss
  src/components/common/input/tag/index.tsx
  src/components/common/input/text/index.tsx
  src/components/common/input/textarea/Textarea.module.scss
  src/components/common/input/textarea/index.tsx
  src/components/common/modal/Modal.module.scss
  src/components/common/modal/ModalPortal.tsx
  src/components/common/modal/index.tsx
  src/components/common/modal/modal-todo/ModalTodo.module.scss
  src/components/common/modal/modal-todo/index.tsx
  src/types/input.ts
Labels: refactor, ui

#72 모달 공통 컴포넌트 UI
  src/components/common/chip/index.tsx
  src/components/common/input/email/Email.module.scss
  src/components/common/input/email/index.tsx
  src/components/common/input/index.tsx
  src/components/common/input/text/Text.module.scss
  src/components/common/input/text/index.tsx
  src/components/common/modal/modal-dashboard/ModalColumn.module.scss
  src/components/common/modal/modal-dashboard/index.tsx
  src/components/common/modal/modal-deletecolumn/ModalDeleteColumn.module.scss
  src/components/common/modal/modal-deletecolumn/index.tsx
  src/components/common/modal/modal-newdash/ModalNewDash.module.scss
  src/components/common/modal/modal-newdash/index.tsx
  src/types/input.ts
Labels: feat, ui

#79 Input 컴포넌트 conflict 해결
  src/components/common/input/index.tsx
Labels: fix

#75 대시보드[id]페이지 column, taskCards api 연동 및 taskCards 무한스크롤 기능 구현
  next.config.mjs
  pages/api/columns.ts
  pages/api/taskCards.ts
  pages/dashboard/[id]/index.tsx
  pages/dashboards/[id]/DashboardId.module.scss
  pages/dashboards/[id]/index.tsx
  src/components/common/layout/Layout.module.scss
  src/components/common/layout/index.tsx
  src/components/dashboard/column/Column.module.scss
  src/components/dashboard/column/column-header/index.tsx
  src/components/dashboard/column/column-layout/ColumnLayout.module.scss
  src/components/dashboard/column/column-layout/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card-date/index.tsx
  src/components/dashboard/column/task-card/TaskCard.module.scss
  src/components/dashboard/column/task-card/index.tsx
  src/components/dashboard/dashboard-button/index.tsx
  src/components/dashboard/header/index.tsx
  src/components/dashboard/side-menu/SideMenu.module.scss
  src/types/commonType.ts
  src/types/dashboard.interface.ts
Labels: feat, refactor

#73 나의 대시보드 페이지 기능 구현 완료
  pages/dashboard/[id]/edit/index.tsx
  pages/mydashboard/index.tsx
  src/components/dashboard/button-container/buttonContainer.module.scss
  src/components/dashboard/button-container/index.tsx
  src/components/dashboard/dashboard-button/index.tsx
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/card/InviteCard.module.scss
  src/components/dashboard/invited-list/card/index.tsx
  src/components/dashboard/invited-list/dashboard/index.tsx
  src/components/dashboard/invited-list/email/index.tsx
  src/components/dashboard/invited-list/index.tsx
  src/components/dashboard/invited-list/member/index.tsx
  src/hooks/useInputSearch.ts
  src/hooks/usePagenation.ts
  src/hooks/usePagenationTest.ts
  src/types/mydashboard.ts
Labels: feat

#80 tag-chip 공통 컴포넌트로 분리
  src/components/common/chip/tag-chip/TagChip.module.scss
  src/components/common/chip/tag-chip/index.tsx
  src/components/common/input/date/react-datepicker.css
  src/components/common/input/tag/index.tsx
  src/components/common/modal/Modal.module.scss
  src/components/common/modal/modal-todo/ModalTodo.module.scss
  src/components/common/modal/modal-todo/index.tsx
Labels: refactor

#83 MangerProfile(담당자) 공통 컴포넌트 생성
  src/components/common/manager-profile/ManagerProfile.module.scss
  src/components/common/manager-profile/index.tsx
  src/components/dashboard/header/DashboardHeader.module.scss
  src/components/dashboard/header/index.tsx
Labels: feat

#86 modal-todo UI
  public/icons/arrow-dropdown.svg
  public/icons/check-gray.svg
  public/icons/circle-purple.svg
  src/components/common/chip/color-chip/ColorChip.module.scss
  src/components/common/chip/color-chip/index.tsx
  src/components/common/chip/progress-chip/ProgressChip.module.scss
  src/components/common/chip/progress-chip/index.tsx
  src/components/common/input/Input.module.scss
  src/components/common/input/date/Date.module.scss
  src/components/common/input/date/react-datepicker.css
  src/components/common/input/dropdown/manager/Manager.module.scss
  src/components/common/input/dropdown/manager/dummyData.ts
  src/components/common/input/dropdown/manager/index.tsx
  src/components/common/input/index.tsx
  src/components/common/input/tag/Tag.module.scss
  src/components/common/input/tag/index.tsx
  src/components/common/input/text/Text.module.scss
  src/components/common/input/text/index.tsx
  src/components/common/input/textarea/Textarea.module.scss
  src/components/common/modal/Modal.module.scss
  src/components/common/modal/modal-todo/index.tsx
  src/types/input.ts
  src/types/member.ts
Labels: feat, ui

#84 InputProfileImage 생성
  package-lock.json
  package.json
  public/icons/edit-img.svg
  src/components/common/input/profile-image/ProfileImage.module.scss
  src/components/common/input/profile-image/index.tsx
  src/components/mypage/profile-form/ProfileForm.module.scss
  src/components/mypage/profile-form/index.tsx
  src/hooks/useUserData.ts
Labels: feat

#90 컬럼 수정 모달 적용
  pages/api/columns.ts
  src/components/common/modal/modal-dashboard/index.tsx
  src/components/dashboard/column/column-header/index.tsx
  src/components/dashboard/column/index.tsx
  src/types/dashboard.interface.ts
Labels: feat

#93 컬럼 삭제, 추가 모달 연결 및 기능 구현 완료
  pages/api/columns.ts
  pages/dashboards/[id]/index.tsx
  src/components/common/modal/modal-dashboard/index.tsx
  src/components/common/modal/modal-deletecolumn/index.tsx
  src/components/dashboard/column/column-header/index.tsx
  src/components/dashboard/column/column-layout/index.tsx
  src/types/dashboard.interface.ts
Labels: feat, refactor

#95 대시보드 페이지, 대시보드 수정 페이지 기능 구현 완료(모달 연결은 아직 X)
  pages/api/dashboards.ts
  pages/api/members.ts
  pages/dashboard/[id]/edit/index.tsx
  pages/dashboards/[id]/edit/DashboardIdEdit.module.scss
  pages/dashboards/[id]/edit/index.tsx
  pages/mydashboard/index.tsx
  src/components/common/back-button/BackButton.module.scss
  src/components/common/back-button/BackButton.tsx
  src/components/common/chip/color-chip/ColorChip.module.scss
  src/components/common/chip/color-chip/index.tsx
  src/components/dashboard/button-container/index.tsx
  src/components/dashboard/dashboard-button/index.tsx
  src/components/dashboard/editor/DashboardEditor.module.scss
  src/components/dashboard/editor/index.tsx
  src/components/dashboard/header/DashboardHeader.module.scss
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/card/index.tsx
  src/components/dashboard/invited-list/dashboard/index.tsx
  src/components/dashboard/invited-list/email/index.tsx
  src/hooks/usePagenation.ts
  src/types/mydashboard.ts
Labels: feat

#98 ModalTask UI
  public/icons/close.svg
  public/icons/popover.svg
  src/components/common/button/border/BorderButton.module.scss
  src/components/common/button/border/index.tsx
  src/components/common/manager-profile/ManagerProfile.module.scss
  src/components/common/manager-profile/index.tsx
  src/components/common/modal/modal-task/ModalTask.module.scss
  src/components/common/modal/modal-task/comment-form/CommentForm.module.scss
  src/components/common/modal/modal-task/comment-form/input.tsx
  src/components/common/modal/modal-task/comment/Comment.module.scss
  src/components/common/modal/modal-task/comment/index.tsx
  src/components/common/modal/modal-task/index.tsx
Labels: ui

#102 이미지 업로드 컴포넌트 교체
  src/components/common/input/dropdown/manager/Manager.module.scss
  src/components/common/input/image-upload/ImageUpload.module.scss
  src/components/common/input/image-upload/index.tsx
  src/components/common/input/index.tsx
  src/components/common/input/profile-image/ProfileImage.module.scss
  src/components/common/input/text/Text.module.scss
  src/components/common/modal/modal-edittodo/ModalEdittodo.module.scss
  src/components/common/modal/modal-edittodo/index.tsx
  src/components/common/modal/modal-todo/ModalTodo.module.scss
  src/components/common/modal/modal-todo/index.tsx
Labels: refactor, remove

#100 나의 대시보드 페이지 ModalNewDash 모달 적용
  pages/api/dashboards.ts
  src/components/common/button/option/index.tsx
  src/components/common/modal/modal-newdash/index.tsx
  src/components/dashboard/button-container/index.tsx
  src/components/dashboard/dashboard-button/index.tsx
  src/components/dashboard/header/index.tsx
  src/types/mydashboard.ts
Labels: feat

#104 계정관리 페이지 리팩토링
  src/components/common/input/new-password/NewPassword.module.scss
  src/components/common/input/password/Password.module.scss
  src/components/common/input/password/index.tsx
  src/components/common/input/text/Text.module.scss
  src/components/mypage/content/Content.module.scss
  src/components/mypage/content/index.tsx
  src/components/mypage/password/Password.module.scss
  src/components/mypage/password/index.tsx
Labels: refactor

#105 할일 카드 생성 모달 연결 및 기능 구현 완료
  pages/api/columns.ts
  pages/api/taskCards.ts
  pages/dashboards/[id]/index.tsx
  src/components/common/modal/modal-todo/index.tsx
  src/components/dashboard/column/column-header/index.tsx
  src/components/dashboard/column/column-layout/ColumnLayout.module.scss
  src/components/dashboard/column/index.tsx
  src/types/dashboard.interface.ts
  src/types/input.ts
  src/utils/formatDate.ts
Labels: feat

#107 모달 스타일링 깨지는 현상 수정
  src/components/common/modal/modal-dashboard/ModalColumn.module.scss
Labels: fix

#108 대시보드 수정하기 모달 적용
  pages/api/dashboards.ts
  pages/api/invitations.ts
  pages/api/members.ts
  pages/dashboards/[id]/edit/index.tsx
  src/components/common/modal/modal-dashboard/index.tsx
  src/components/dashboard/button-container/index.tsx
  src/components/dashboard/editor/index.tsx
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/card/index.tsx
  src/components/dashboard/invited-list/dashboard/index.tsx
  src/components/dashboard/invited-list/email/index.tsx
  src/hooks/usePagenation.ts
  src/types/mydashboard.ts
Labels: feat

#110 계정관리에서 프로필 저장 시 header에도 바로 적용
  src/components/common/layout/index.tsx
  src/components/dashboard/header/index.tsx
  src/components/mypage/profile-form/index.tsx
  src/context/users.tsx
  src/hooks/useUserData.ts
Labels: fix

#111 이미지 업로드 함수 분리
  pages/api/imageUpload.ts
  src/components/mypage/profile-form/index.tsx
Labels: refactor

#116 헤더 프로필 클릭 시 팝오버 생성
  src/components/common/manager-profile/ManagerProfile.module.scss
  src/components/common/manager-profile/index.tsx
  src/components/dashboard/header/index.tsx
Labels: feat

#120 할일 수정 및 생성 모달 작업
  pages/api/taskCards.ts
  pages/api/users.ts
  src/components/common/modal/index.tsx
  src/components/common/modal/modal-edittodo/index.tsx
  src/components/common/modal/modal-todo/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card/TaskCard.module.scss
  src/components/dashboard/column/task-card/index.tsx
  src/constants/date.ts
Labels: feat

#124 fetchGetUser와 겹치는 부분 수정
  src/context/users.tsx
Labels: refactor

#125 ModalTask 연결, 댓글 get,put,delete 기능, 무한스크롤 구현
  pages/api/comments.ts
  src/components/common/modal/modal-deletecolumn/index.tsx
  src/components/common/modal/modal-task/ModalTask.module.scss
  src/components/common/modal/modal-task/comment-form/index.tsx
  src/components/common/modal/modal-task/comment/Comment.module.scss
  src/components/common/modal/modal-task/comment/index.tsx
  src/components/common/modal/modal-task/index.tsx
  src/components/dashboard/column/task-card/TaskCard.module.scss
  src/components/dashboard/column/task-card/index.tsx
  src/types/dashboard.interface.ts
Labels: feat

#127 댓글 생성 기능 추가 & 모달 수정 컴포넌트 이동
  pages/api/comments.ts
  pages/dashboards/[id]/index.tsx
  src/components/common/chip/progress-chip/index.tsx
  src/components/common/modal/modal-task/comment-form/index.tsx
  src/components/common/modal/modal-task/comment-form/input.tsx
  src/components/common/modal/modal-task/index.tsx
  src/components/dashboard/column/column-layout/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card/index.tsx
  src/types/dashboard.interface.ts
Labels: fix, feat

#128 나의 대시보드, 대시보드 수정 페이지 context 적용
  pages/api/dashboards.ts
  pages/dashboards/[id]/edit/index.tsx
  pages/mydashboard/index.tsx
  src/components/common/layout/index.tsx
  src/components/dashboard/button-container/index.tsx
  src/components/dashboard/editor/index.tsx
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/card/index.tsx
  src/components/dashboard/invited-list/dashboard/index.tsx
  src/components/dashboard/invited-list/email/index.tsx
  src/components/dashboard/invited-list/member/index.tsx
  src/components/dashboard/side-menu/dashboard-list-section/dashboard-list/index.tsx
  src/components/dashboard/side-menu/dashboard-list-section/index.tsx
  src/components/dashboard/side-menu/dashboard-list-section/list-header/index.tsx
  src/context/dashboards.tsx
  src/context/inviteeEmail.tsx
  src/context/members.tsx
  src/hooks/usePagination.ts
  src/types/mydashboard.ts
Labels: feat

#133 할 일 수정 모달 : 상태 수정
  pages/dashboards/[id]/index.tsx
  src/components/common/input/dropdown/progress/index.tsx
  src/components/common/input/index.tsx
  src/components/common/modal/modal-edittodo/index.tsx
  src/components/common/modal/modal-task/index.tsx
  src/types/dashboard.interface.ts
  src/types/input.ts
Labels: feat

#132 ModalTodo(할일 생성) Tag, Image 생성 기능 추가
  pages/api/imageUpload.ts
  pages/api/taskCards.ts
  src/components/common/input/index.tsx
  src/components/common/input/tag/index.tsx
  src/components/common/modal/modal-task/index.tsx
  src/components/common/modal/modal-todo/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card-date/index.tsx
  src/components/dashboard/column/task-card/TaskCard.module.scss
  src/components/dashboard/column/task-card/index.tsx
  src/types/dashboard.interface.ts
  src/types/input.ts
Labels: feat

#136 이미지 렌더링 오류 해결
  src/components/common/modal/modal-todo/index.tsx
Labels: fix

#139 계정 관리 페이지 UI 수정
  src/components/common/modal/modal-alert/ModalAlert.module.scss
  src/components/mypage/password/index.tsx
  src/components/mypage/profile-form/ProfileForm.module.scss
  src/components/mypage/profile-form/index.tsx
Labels: refactor, ui

#140 Toast 기능 일부 적용
  pages/dashboards/[id]/edit/index.tsx
  pages/mypage/index.tsx
  src/components/dashboard/editor/index.tsx
  src/components/dashboard/invited-list/email/index.tsx
  src/components/mypage/password/index.tsx
  src/components/mypage/profile-form/index.tsx
  src/components/toast/Toast.module.scss
  src/components/toast/index.tsx
  src/context/toast.tsx
Labels: feat, ui

#143 taskCards가 배열로 들어오지 않을 경우 에러 처리 & edit 오류 수정
  src/components/common/modal/modal-task/index.tsx
  src/components/common/modal/modal-todo/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card/index.tsx
Labels: fix

#144 card이미지가 null값일 때 처리, 댓글 빈 내용일 때 비활성화, 아이콘 taskCard연결
  src/components/common/manager-profile/index.tsx
  src/components/common/modal/modal-task/comment-form/index.tsx
  src/components/common/modal/modal-task/index.tsx
  src/components/dashboard/column/task-card/TaskCard.module.scss
  src/components/dashboard/column/task-card/index.tsx
Labels: feat, refactor

#146 할 일 수정 모달 작업 완료
  pages/api/members.ts
  src/components/common/input/dropdown/manager/dummyData.ts
  src/components/common/input/dropdown/manager/index.tsx
  src/components/common/input/dropdown/progress/index.tsx
  src/components/common/input/tag/index.tsx
  src/components/common/modal/modal-edittodo/index.tsx
  src/components/common/modal/modal-task/ModalTask.module.scss
  src/components/common/modal/modal-task/index.tsx
  src/components/common/modal/modal-todo/index.tsx
Labels: fix, feat

#148 회원가입 및 로그인 UI 수정
  src/components/common/input/email/Email.module.scss
  src/components/common/input/password/Password.module.scss
  src/components/login-signup/form/Form.module.scss
  src/components/login-signup/form/signup/index.tsx
Labels: fix

#149 나의 대시보드 반응형 적용, 유저 기본 이미지 구현 및 적용
  pages/api/dashboards.ts
  pages/mydashboard/MyDashboard.module.scss
  src/components/common/chip/color-chip/index.tsx
  src/components/common/input/dropdown/manager/index.tsx
  src/components/common/manager-profile/ManagerProfile.module.scss
  src/components/common/manager-profile/index.tsx
  src/components/common/modal/modal-task/comment/index.tsx
  src/components/common/modal/modal-task/index.tsx
  src/components/common/user-default-img/UserDefaultImg.module.scss
  src/components/common/user-default-img/index.tsx
  src/components/dashboard/button-container/buttonContainer.module.scss
  src/components/dashboard/column/task-card/index.tsx
  src/components/dashboard/dashboard-button/dashboardButton.module.scss
  src/components/dashboard/dashboard-button/index.tsx
  src/components/dashboard/editor/index.tsx
  src/components/dashboard/header/DashboardHeader.module.scss
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/InvitedList.module.scss
  src/components/dashboard/invited-list/card/InviteCard.module.scss
  src/components/dashboard/invited-list/card/index.tsx
  src/components/dashboard/invited-list/dashboard/InviteListDashboard.module.scss
  src/components/dashboard/invited-list/dashboard/index.tsx
  src/components/dashboard/invited-list/member/index.tsx
  src/components/dashboard/pagenation-button/PagenationButton.module.scss
  src/components/dashboard/side-menu/dashboard-list-section/index.tsx
  src/components/dashboard/side-menu/dashboard-list-section/list-header/ListHeader.module.scss
  src/constants/colorchip.ts
  src/context/dashboards.tsx
  src/context/members.tsx
  src/types/mydashboard.ts
  src/utils/userIdToColorIdx.ts
Labels: feat, ui

#151 토스트 사자리는 순서 수정
  src/components/toast/index.tsx
Labels: fix

#153 드랍다운 에서 ProfileImg 적용 안된거 수정
  src/components/common/input/dropdown/manager/index.tsx
  src/components/dashboard/header/DashboardHeader.module.scss
Labels: fix, feat

#155 렌더링 시 더보기 버튼 오류 수정, 컬럼 totalCount 수정, 로딩 스피너 적용
  pages/api/taskCards.ts
  pages/dashboards/[id]/edit/DashboardIdEdit.module.scss
  pages/mydashboard/MyDashboard.module.scss
  src/components/common/layout/Layout.module.scss
  src/components/common/layout/index.tsx
  src/components/common/modal/modal-task/ModalTask.module.scss
  src/components/common/modal/modal-task/index.tsx
  src/components/common/modal/modal-todo/index.tsx
  src/components/common/spinner/Spinner.module.scss
  src/components/common/spinner/index.tsx
  src/components/dashboard/column/Column.module.scss
  src/components/dashboard/column/column-header/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card/TaskCard.module.scss
  src/components/dashboard/column/task-card/index.tsx
  src/components/dashboard/side-menu/SideMenu.module.scss
  src/types/dashboard.interface.ts
Labels: fix, feat

#156 전체적 레이아웃 개선 및 수정 사항
  pages/dashboards/[id]/DashboardId.module.scss
  pages/dashboards/[id]/edit/DashboardIdEdit.module.scss
  pages/mydashboard/MyDashboard.module.scss
  src/components/dashboard/dashboard-button/dashboardButton.module.scss
Labels: refactor

#158 날짜 삭제 버튼, 할일 수정 후 데이터 업데이트
  pages/api/taskCards.ts
  src/components/common/input/date/Date.module.scss
  src/components/common/input/date/index.tsx
  src/components/common/input/dropdown/manager/Manager.module.scss
  src/components/common/input/index.tsx
  src/components/common/input/tag/index.tsx
  src/components/common/modal/modal-edittodo/index.tsx
  src/components/common/modal/modal-task/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card/index.tsx
Labels: fix, feat

#157 대시보드 수정 페이지 반응형 적용
  pages/dashboards/[id]/edit/DashboardIdEdit.module.scss
  pages/mydashboard/MyDashboard.module.scss
  src/components/common/back-button/BackButton.module.scss
  src/components/common/input/text/Text.module.scss
  src/components/common/input/text/index.tsx
  src/components/dashboard/dashboard-button/dashboardButton.module.scss
  src/components/dashboard/editor/DashboardEditor.module.scss
  src/components/dashboard/editor/index.tsx
  src/components/dashboard/header/DashboardHeader.module.scss
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/card/InviteCard.module.scss
  src/components/dashboard/invited-list/card/index.tsx
  src/components/dashboard/invited-list/email/InviteListEmail.module.scss
  src/components/dashboard/invited-list/member/InviteListMember.module.scss
  src/components/dashboard/pagenation-button/PagenationButton.module.scss
  src/context/dashboards.tsx
  src/hooks/useMobileSizeChange.ts
Labels: style, ui

#163 프로젝트 전체 타입 정리
  pages/api/columns.ts
  pages/api/comments.ts
  pages/api/taskCards.ts
  pages/dashboards/[id]/index.tsx
  src/components/common/input/date/index.tsx
  src/components/common/input/dropdown/manager/index.tsx
  src/components/common/input/dropdown/progress/index.tsx
  src/components/common/input/index.tsx
  src/components/common/input/new-password/index.tsx
  src/components/common/input/password/index.tsx
  src/components/common/input/tag/index.tsx
  src/components/common/input/text/index.tsx
  src/components/common/layout/index.tsx
  src/components/common/manager-profile/index.tsx
  src/components/common/modal/modal-alert/index.tsx
  src/components/common/modal/modal-confirm/index.tsx
  src/components/common/modal/modal-dashboard/index.tsx
  src/components/common/modal/modal-deletecolumn/index.tsx
  src/components/common/modal/modal-edittodo/index.tsx
  src/components/common/modal/modal-newdash/index.tsx
  src/components/common/modal/modal-task/comment-form/index.tsx
  src/components/common/modal/modal-task/comment/index.tsx
  src/components/common/modal/modal-task/index.tsx
  src/components/common/modal/modal-todo/index.tsx
  src/components/common/user-default-img/index.tsx
  src/components/dashboard/column/column-header/index.tsx
  src/components/dashboard/column/column-layout/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card-date/index.tsx
  src/components/dashboard/column/task-card/index.tsx
  src/components/login-signup/form/signup/index.tsx
  src/context/dashboards.tsx
  src/context/inviteeEmail.tsx
  src/context/members.tsx
  src/context/toast.tsx
  src/context/users.tsx
  src/types/common.ts
  src/types/dashboard.ts
  src/types/input.ts
  src/types/modal.ts
  src/utils/validation.ts
Labels: refactor

#166 버그 수정 & 로그아웃 구현 & favicon
  pages/_app.tsx
  public/favicon.ico
  src/components/common/input/index.tsx
  src/components/common/input/new-password/NewPassword.module.scss
  src/components/common/input/password/index.tsx
  src/components/common/manager-profile/index.tsx
  src/components/dashboard/column/task-card/index.tsx
  src/components/login-signup/form/login/index.tsx
  src/components/mypage/password/Password.module.scss
  src/components/mypage/password/index.tsx
  src/types/input.ts
Labels: fix, feat

#165 나의 대시보드 페이지 css 충돌 수정
  pages/mydashboard/MyDashboard.module.scss
  src/components/dashboard/side-menu/dashboard-list-section/list-header/ListHeader.module.scss
Labels: style

#175 ModalEdittodo에서 카드의 다른 컬럼으로의 이동이 즉시 반영되지 않는 현상 수정 외 2가지
  next.config.mjs
  pages/api/columns.ts
  pages/dashboards/[id]/index.tsx
  src/components/common/input/dropdown/progress/index.tsx
  src/components/common/modal/Modal.module.scss
  src/components/common/modal/index.tsx
  src/components/common/modal/modal-dashboard/index.tsx
  src/components/common/modal/modal-deletecolumn/index.tsx
  src/components/common/modal/modal-edittodo/index.tsx
  src/components/common/modal/modal-task/index.tsx
  src/components/dashboard/column/column-header/index.tsx
  src/components/dashboard/column/column-layout/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card/index.tsx
  src/types/modal.ts
Labels: fix, refactor

#176 사이드바 대시보드 리스트 스크롤 구현
  public/icons/temp-circle-1.svg
  public/icons/temp-circle-2.svg
  public/icons/temp-circle-3.svg
  public/icons/temp-circle-4.svg
  public/icons/temp-circle-5.svg
  public/icons/temp-circle-6.svg
  src/components/dashboard/button-container/index.tsx
  src/components/dashboard/invited-list/dashboard/InviteListDashboard.module.scss
  src/components/dashboard/side-menu/dashboard-list-section/DashboardListSection.module.scss
  src/components/dashboard/side-menu/dashboard-list-section/dashboard-list/index.tsx
  src/components/dashboard/side-menu/dashboard-list-section/index.tsx
  src/context/dashboards.tsx
Labels: feat, refactor

#177 메인 페이지 서비스 소개 글 작성
  src/components/landing/header/Header.module.scss
  src/components/landing/header/index.tsx
Labels: ui

#178 Comment edit input css추가, ModalTask, Commnet, TaskCard css 수정
  src/components/common/button/border/BorderButton.module.scss
  src/components/common/modal/modal-task/ModalTask.module.scss
  src/components/common/modal/modal-task/comment/Comment.module.scss
  src/components/common/modal/modal-task/comment/index.tsx
  src/components/common/modal/modal-task/index.tsx
  src/components/dashboard/column/task-card/TaskCard.module.scss
  src/styles/reset.css
Labels: fix

#190 대시보드 헤더 화면 고정
  src/components/common/layout/Layout.module.scss
Labels: bug-major

#191 배포에 필요한 추가 설정 완료
  netlify.toml
  package-lock.json
  package.json
Labels: feat

#194 footer 없는 페이지로 이동 막음
  src/components/landing/footer/index.tsx
Labels: bug-minor

#195 프로필 변경 시 버그 수정
  src/components/mypage/profile-form/index.tsx
Labels: bug-major

#193 README 작성
  README.md
Labels: docs

#197 모달 UI
  pages/dashboards/[id]/edit/index.tsx
  pages/dashboards/[id]/index.tsx
  src/components/common/input/date/Date.module.scss
  src/components/common/modal/index.tsx
  src/components/common/modal/modal-dashboard/ModalColumn.module.scss
  src/components/common/modal/modal-deletecolumn/ModalDeleteColumn.module.scss
  src/components/common/modal/modal-task/index.tsx
  src/components/dashboard/button-container/index.tsx
  src/components/dashboard/column/column-header/index.tsx
  src/components/dashboard/column/index.tsx
  src/components/dashboard/column/task-card/index.tsx
  src/components/dashboard/editor/index.tsx
  src/components/dashboard/header/index.tsx
  src/components/dashboard/invited-list/card/index.tsx
  src/components/dashboard/invited-list/email/index.tsx
  src/components/dashboard/side-menu/dashboard-list-section/list-header/index.tsx
  src/components/login-signup/form/login/index.tsx
  src/components/mypage/password/index.tsx
Labels: bug-minor

#196 사이드메뉴 컬럼 리스트 스크롤 높이 수정, 페이지 네이션 버튼 수정, 대시보드 삭제 후 뒤로가기 안되게 수정
  pages/dashboards/[id]/edit/index.tsx
  public/images/small-arrow-black-left.png
  public/images/small-arrow-black-right.png
  src/components/dashboard/pagenation-button/index.tsx
  src/components/dashboard/side-menu/dashboard-list-section/DashboardListSection.module.scss
  src/components/dashboard/side-menu/dashboard-list-section/index.tsx
Labels: bug-minor

#199 대시보드 삭제 후 /mydashboard 로 이동하게 구현
  pages/mydashboard/MyDashboard.module.scss
  src/context/dashboards.tsx
Labels: bug-major

#200 긴 컬럼명 있을 때 디자인 깨짐 수정
  pages/dashboards/[id]/index.tsx
  src/components/common/modal/modal-edittodo/index.tsx
  src/components/dashboard/column/column-header/ColumnHeader.module.scss
  src/components/dashboard/column/column-layout/index.tsx
Labels: bug-minor
